### ISSUE TITLE
Spheres are disabled too

### ISSUE THREAD

**Issue by aggelosQQ** [ImmaFreedom-Dev/IF-WorldEdit#2]
@ImmaFreedom-Dev/member @OutOfYourMind

**Comment by tylerhyperHD** [comment]
Spheres are disabled due to griefers constantly not using them for what they are made for. Denied.

**Comment by aggelosQQ** [comment]
No, that is why we have coreprotect.
Unblock them.

**Comment by tylerhyperHD** [comment]
Re-denied again.
1) The only thing they are used for is to grief
2) It is one less thing to worry about
3) I NEVER SEE ANYONE USE IT FOR WHAT IT IS USED FOR OKAY ENUGH SAID

**Comment by tylerhyperHD** [comment]
I will only unblock it actually if you give me valid reasoning why it should be unblocked, and yes, the reason must outweigh the disadvantages.

**Comment by aggelosQQ** [comment]
Because I actually build with it, people are asking me to unblock it, I think it's enough. I want it unblocked, so please do it.

**Comment by tylerhyperHD** [comment]
I decided that since only admins know how to properly use it that I will make it for admins only. Ops just usually use it to crash the server so imma just do that instead.
